### ISSUE TITLE
Rever a logo em vetorial para imprimir

### ISSUE THREAD

**Issue by Thithi32** [CodeForCuritiba/resgateanimal#3]
Precisamos da logo para poder imprimir o adesivo para a ambulância. Alguém pode ajudar?

**Comment by ikenaga** [comment]
Logo do Code?

**Comment by thierrydelbart** [comment]
Logo do resgate animal http://resgateanimal.eco.br/images/banner.jpg

**Comment by ikenaga** [comment]
Refiz a logomarca e adicionei no diretório logo. No formato SVG não consegui reproduzir o degradee do shape. No formato Corel Draw X8 está com o degradee.

**Comment by thierrydelbart** [comment]
Acredito que vai ser ainda melhor. Valeu @ikenaga !
